{% set name = "arize-phoenix" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix-{{ version }}.tar.gz
  sha256: f4bb3a158ab0d6a937ee4d6205fe63658459fa2b8e81b7327bf90b505be90b91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8,<3.11
    - numpy
    - pandas
    - umap-learn
    - hdbscan
    - starlette
    - uvicorn
    - psutil
    - strawberry-graphql ==0.155.3
    - pyarrow
    - typing-extensions
    - scipy
    - portpicker
    - wrapt

test:
  imports:
    - phoenix
  commands:
    - pip check
  requires:
    - pip

about:
  summary: ML Observability in your notebook
  home: https://github.com/Arize-ai/phoenix
  doc_url: https://docs.arize.com/phoenix
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - rogerhyang
    - michaelschiff
    - fjcasti1
    - axiomofjoy
